# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    xcclean(workspace: "Loitr.xcworkspace", scheme: "Loitr")
    increment_build_number(build_number: latest_testflight_build_number(app_identifier: "com.mobilefirst.Loitr", platform: "ios") + 1, xcodeproj: "Loitr.xcodeproj")
    changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    build_app(workspace: "Loitr.xcworkspace", scheme: "Loitr")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
